# Generated by Django 4.1.3 on 2022-12-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvlcblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(max_length=4000),
        ),
    ]
